services:
  - type: web
    name: miulsacuu-frontend
    runtime: static
    rootDir: mi-ulsa-app
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
